version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME}
      - SPRING_R2DBC_URL=${SPRING_R2DBC_URL}
      - SPRING_R2DBC_USERNAME=${SPRING_R2DBC_USERNAME}
      - SPRING_R2DBC_PASSWORD=${SPRING_R2DBC_PASSWORD}
      - OTLP_ENDPOINT=${OTLP_ENDPOINT}
      - PORT=${PORT:-8080}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8080}/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - claims-network
  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    networks:
      - claims-network

volumes:
  postgres_data:

networks:
  claims-network:
    driver: bridge 